version: "3.9"
services:
  app:
    image: wordpress:v1.0
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./php-fpm/www.conf
        target: /etc/php/7.4/fpm/pool.d/www.conf
      - type: bind
        source: ./php-fpm/php-fpm.conf
        target: /etc/php/7.4/fpm/php-fpm.conf
      - type: bind
        source: ./supervisord/supervisord.conf
        target: /etc/supervisor/conf.d/supervisord.conf
      - type: bind
        source: ./wordpress
        target: /var/www/html 

    ports:
      - "80:80"
      - "443:443"
    restart: always
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp
    ports:
      - "3306:3306"
volumes:
  db_data: {}
