- name: creating working directory
  file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775
    recurse: yes
- name: copying content from host to remote
  copy:
    src: ./
    dest: "{{ project_dir }}"
    mode: '0755'
- name: prepare docker repos
  apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - sudo
      - python3-dev
    state: present
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
- name: Install Docker Engine
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io 
      - docker-compose-plugin
    state: present
- name: add user to docker group
  user: 
    name: "{{ user }}"
    groups: docker
- name: install docker-compose
  command: curl -SL https://github.com/docker/compose/releases/download/v2.11.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
- file:
    path: /usr/local/bin/docker-compose
    mode: '0777'
    owner: "{{ user }}"
- name: install python3-pip
  apt:
    update_cache: yes
    name: python3-pip
    state: present
- name: install docker through pip
  pip:
    name: docker
    state: present 
